language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t rlustemberg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rlustemberg/react-test npm test -- --coverage

after_success:
  - docker build -t rlustemberg/multi-client ./client
  - docker build -t rlustemberg/multi-nginx ./nginx
  - docker build -t rlustemberg/multi-server ./server
  - docker build -t rlustemberg/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to Docker Hub
  - docker push rlustemberg/multi-client
  - docker push rlustemberg/multi-nginx
  - docker push rlustemberg/multi-server
  - docker push rlustemberg/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-651245374920"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
